name = "server"
main = "./entry.server.tsx"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "USERS"
id = "54a67a72e2184faa86397c3a75f3f99d"

[durable_objects]
bindings = [
  { name = "TODO_LIST", class_name = "TodoList" },
  { name = "USER", class_name = "User" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TodoList", "User"]
