name = "server"
main = "./entry.server.tsx"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "USERS"
id = "54a67a72e2184faa86397c3a75f3f99d"

[durable_objects]
bindings = [{ name = "COUNTER", class_name = "Counter" }]

[[migrations]]
tag = "v1"
new_classes = ["Counter"]
